import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";
import {  Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Uttara Medic - Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${poppins.className} max-w-[1920px] mx-auto  bg-bgColor`}
        >
          {children}
        </body>
      </html>
    </Providers>
  );
}
